server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: jdbc:mysql://193.203.160.126/identity_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true